### ISSUE TITLE
invalid discord invite

### ISSUE THREAD

**Issue by potato-baby** [nxxh447/nxxh447.github.io#1]
because i thought i could actually fix your invalid discord invite by replacing it with new one so i forked your repo and i tried to fix it but i couldnt, sorry for my lack of knowledge 😵🥵

**Comment by potato-baby** [comment]
update the discord invite so people could directly join easily through the site

**Comment by potato-baby** [comment]
nxxh, i know github isnt a place to discuss your personal arguments, i want to apologize because of my past actions, please forgive me im really changed, can you talk to me on discord please 😭😭😭

**Comment by potato-baby** [comment]
because i want you to be my friend again

**Comment by TriDiscord** [comment]
ok i know you've changed and all but:
can you please not take your personal issues to FUCKING GITHUB
